Algoritmo "get_name"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2017
Var
// Seção de Declarações das variáveis 

name: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite Seu Nome")

leia(name)


escreva("Seu Nome é"+ name)


Fimalgoritmo