Algoritmo "SOMA"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2017
Var
// Seção de Declarações das variáveis 
n1, n2,resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
leia(n1)
leia(n2)

 resultado <- n1+n2



  escreva("SOMA:", resultado)


Fimalgoritmo